//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureSubmit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecureSubmit.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HPS SDK has not been properly configured. Please make sure to initialize the config either in a service constructor or in your App.config or Web.config file..
        /// </summary>
        public static string Exception_Message_InvalidConfig {
            get {
                return ResourceManager.GetString("Exception_Message_InvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide either a transactionId or a clientTransactionId.
        /// </summary>
        public static string HpsCheckService_Invalid_Input_Id {
            get {
                return ResourceManager.GetString("HpsCheckService_Invalid_Input_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction ID..
        /// </summary>
        public static string Invalid_Transaction_ID {
            get {
                return ResourceManager.GetString("Invalid_Transaction_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;exception_mappings&quot;:[{&quot;object&quot;:&quot;exception_mapping&quot;,&quot;category&quot;:&quot;issuer&quot;,&quot;exception_codes&quot;:[&quot;02&quot;,&quot;03&quot;,&quot;04&quot;,&quot;05&quot;,&quot;41&quot;,&quot;43&quot;,&quot;44&quot;,&quot;51&quot;,&quot;56&quot;,&quot;61&quot;,&quot;62&quot;,&quot;63&quot;,&quot;65&quot;,&quot;78&quot;],&quot;mapping_type&quot;:&quot;CardException&quot;,&quot;mapping_code&quot;:&quot;card_declined&quot;,&quot;mapping_message&quot;:&quot;Exception_Message_CardDeclined&quot;},{&quot;object&quot;:&quot;exception_mapping&quot;,&quot;category&quot;:&quot;issuer&quot;,&quot;exception_codes&quot;:[&quot;06&quot;,&quot;07&quot;,&quot;12&quot;,&quot;15&quot;,&quot;19&quot;,&quot;12&quot;,&quot;52&quot;,&quot;53&quot;,&quot;57&quot;,&quot;58&quot;,&quot;76&quot;,&quot;77&quot;,&quot;91&quot;,&quot;96&quot;,&quot;EC&quot;],&quot;mapping_type&quot;:&quot;CardException&quot;,&quot;mapping_code&quot;:&quot;processing_error&quot;,&quot;mapping_message&quot;:&quot;....
        /// </summary>
        public static string Json_Exception_Mappings {
            get {
                return ResourceManager.GetString("Json_Exception_Mappings", resourceCulture);
            }
        }
    }
}
